<?php
/**
 * Регистрация ACF полей для темы Push
 */

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_hero_section',
    'title' => 'Hero Section - Главная секция',
    'fields' => array(
        // Группа: Заголовок
        array(
            'key' => 'field_hero_title_group',
            'label' => 'Заголовок',
            'name' => 'hero_title_group',
            'type' => 'group',
            'instructions' => 'Настройки заголовка hero секции',
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_hero_title_line1',
                    'label' => 'Первая строка',
                    'name' => 'line1',
                    'type' => 'text',
                    'instructions' => 'Первая строка заголовка (например: "Стильний")',
                    'default_value' => 'Стильний',
                    'placeholder' => 'Стильний',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_hero_title_line2',
                    'label' => 'Вторая строка',
                    'name' => 'line2',
                    'type' => 'text',
                    'instructions' => 'Вторая строка заголовка (например: "SMM для тебе")',
                    'default_value' => 'SMM для тебе',
                    'placeholder' => 'SMM для тебе',
                    'required' => 0,
                ),
            ),
        ),
        // Описание
        array(
            'key' => 'field_hero_description',
            'label' => 'Описание',
            'name' => 'hero_description',
            'type' => 'textarea',
            'instructions' => 'Текст описания в hero секции',
            'default_value' => 'Ми – Push Agency, креативне агентство для соцмереж, яке поєднує системний підхід і нестандартні ідеї. Тут ти знайдеш сучасний дизайн, зрозумілу навігацію і рішення, які реально працюють.',
            'rows' => 4,
            'required' => 0,
        ),
        // Группа: Кнопка
        array(
            'key' => 'field_hero_button_group',
            'label' => 'Кнопка',
            'name' => 'hero_button_group',
            'type' => 'group',
            'instructions' => 'Настройки кнопки в hero секции',
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_hero_button_text',
                    'label' => 'Текст кнопки',
                    'name' => 'text',
                    'type' => 'text',
                    'instructions' => 'Текст на кнопке',
                    'default_value' => 'Зв\'язатись з нами',
                    'placeholder' => 'Зв\'язатись з нами',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_hero_button_link',
                    'label' => 'Ссылка',
                    'name' => 'link',
                    'type' => 'url',
                    'instructions' => 'URL ссылки кнопки',
                    'default_value' => '#',
                    'placeholder' => '#',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_hero_button_target',
                    'label' => 'Целевая ссылка',
                    'name' => 'target',
                    'type' => 'select',
                    'instructions' => 'Куда откроется ссылка (сайт, новое окно)',
                    'choices' => array(
                        '_self' => 'На текущей странице',
                        '_blank' => 'В новом окне',
                    ),
                    'default_value' => '_self',
                    'required' => 1,
                ),
            ),
        ),
        // Изображение Push
        array(
            'key' => 'field_hero_push_image',
            'label' => 'Изображение Push',
            'name' => 'hero_push_image',
            'type' => 'image',
            'instructions' => 'Изображение Push в hero секции (если не указано, будет использовано изображение по умолчанию)',
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'required' => 0,
        ),
        // Фоновые элементы (Repeater)
        array(
            'key' => 'field_hero_bg_items',
            'label' => 'Фоновые элементы (соцсети)',
            'name' => 'hero_bg_items',
            'type' => 'repeater',
            'instructions' => 'Добавьте элементы фона (иконки соцсетей). Если не заполнено, будут использованы элементы по умолчанию.',
            'layout' => 'block',
            'button_label' => 'Добавить элемент',
            'collapsed' => 'field_hero_bg_item_class',
            'sub_fields' => array(
                array(
                    'key' => 'field_hero_bg_item_image',
                    'label' => 'Изображение',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => 'Изображение иконки соцсети',
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_hero_bg_item_class',
                    'label' => 'CSS класс',
                    'name' => 'css_class',
                    'type' => 'text',
                    'instructions' => 'CSS класс для элемента (например: item-inst, item-fb, item-tiktok)',
                    'default_value' => '',
                    'placeholder' => 'item-inst',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_hero_bg_item_alt',
                    'label' => 'Alt текст',
                    'name' => 'alt',
                    'type' => 'text',
                    'instructions' => 'Alt текст для изображения',
                    'default_value' => '',
                    'placeholder' => 'inst',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_hero_bg_item_shadows',
                    'label' => 'Количество теней',
                    'name' => 'shadows_count',
                    'type' => 'number',
                    'instructions' => 'Количество элементов теней (0-3). Если 0, тени не будут отображаться.',
                    'default_value' => 0,
                    'min' => 0,
                    'max' => 3,
                    'step' => 1,
                    'required' => 0,
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Настройки для Hero секции на главной странице',
));

// Группа полей для Services секции
acf_add_local_field_group(array(
    'key' => 'group_services_section',
    'title' => 'Services Section - Секция услуг',
    'fields' => array(
        // Заголовок
        array(
            'key' => 'field_services_title_group',
            'label' => 'Заголовок',
            'name' => 'services_title_group',
            'type' => 'group',
            'instructions' => 'Настройки заголовка секции услуг',
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_services_title_part1',
                    'label' => 'Первая часть',
                    'name' => 'part1',
                    'type' => 'text',
                    'instructions' => 'Первая часть заголовка (например: "Наші")',
                    'default_value' => 'Наші',
                    'placeholder' => 'Наші',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_services_title_part2',
                    'label' => 'Вторая часть (в span)',
                    'name' => 'part2',
                    'type' => 'text',
                    'instructions' => 'Вторая часть заголовка, которая будет в span (например: "послуги")',
                    'default_value' => 'послуги',
                    'placeholder' => 'послуги',
                    'required' => 1,
                ),
            ),
        ),
        // Repeater для услуг
        array(
            'key' => 'field_services_items',
            'label' => 'Услуги',
            'name' => 'services_items',
            'type' => 'repeater',
            'instructions' => 'Добавьте услуги для отображения в слайдере. Если не заполнено, будут использованы услуги по умолчанию.',
            'layout' => 'block',
            'button_label' => 'Добавить услугу',
            'collapsed' => 'field_services_item_title',
            'sub_fields' => array(
                array(
                    'key' => 'field_services_item_image',
                    'label' => 'Иконка',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => 'Иконка услуги',
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_services_item_title',
                    'label' => 'Заголовок',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => 'Заголовок услуги (например: "01/SMM-консалтинг")',
                    'default_value' => '',
                    'placeholder' => '01/SMM-консалтинг',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_services_item_description',
                    'label' => 'Описание',
                    'name' => 'description',
                    'type' => 'textarea',
                    'instructions' => 'Описание услуги',
                    'default_value' => '',
                    'placeholder' => 'Повний аудит профілю з обговоренням і наданням SMM стратегії',
                    'rows' => 3,
                    'required' => 1,
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options',
            ),
        ),
    ),
    'menu_order' => 1,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Настройки для секции услуг на главной странице',
));

// Группа полей для Why Us секции
acf_add_local_field_group(array(
    'key' => 'group_whyus_section',
    'title' => 'Why Us Section - Секция "Почему мы"',
    'fields' => array(
        // Эмодзи изображение
        array(
            'key' => 'field_whyus_emoji',
            'label' => 'Эмодзи изображение',
            'name' => 'whyus_emoji',
            'type' => 'image',
            'instructions' => 'Изображение эмодзи для секции (если не указано, будет использовано изображение по умолчанию)',
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'required' => 0,
        ),
        // Заголовок
        array(
            'key' => 'field_whyus_title_group',
            'label' => 'Заголовок',
            'name' => 'whyus_title_group',
            'type' => 'group',
            'instructions' => 'Настройки заголовка секции',
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_whyus_title_first',
                    'label' => 'Первая часть',
                    'name' => 'first',
                    'type' => 'text',
                    'instructions' => 'Первая часть заголовка (например: "чому")',
                    'default_value' => 'чому',
                    'placeholder' => 'чому',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_whyus_title_second',
                    'label' => 'Вторая часть',
                    'name' => 'second',
                    'type' => 'text',
                    'instructions' => 'Вторая часть заголовка (например: "саме ми?")',
                    'default_value' => 'саме ми?',
                    'placeholder' => 'саме ми?',
                    'required' => 1,
                ),
            ),
        ),
        // Repeater для элементов
        array(
            'key' => 'field_whyus_items',
            'label' => 'Элементы',
            'name' => 'whyus_items',
            'type' => 'repeater',
            'instructions' => 'Добавьте элементы для секции "Почему мы". Если не заполнено, будут использованы элементы по умолчанию.',
            'layout' => 'block',
            'button_label' => 'Добавить элемент',
            'collapsed' => 'field_whyus_item_title',
            'sub_fields' => array(
                array(
                    'key' => 'field_whyus_item_number',
                    'label' => 'Номер',
                    'name' => 'number',
                    'type' => 'text',
                    'instructions' => 'Номер элемента (например: "01", "02")',
                    'default_value' => '',
                    'placeholder' => '01',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_whyus_item_title',
                    'label' => 'Заголовок',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => 'Заголовок элемента',
                    'default_value' => '',
                    'placeholder' => 'Кожен крок має сенс',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_whyus_item_description',
                    'label' => 'Описание',
                    'name' => 'description',
                    'type' => 'textarea',
                    'instructions' => 'Описание элемента',
                    'default_value' => '',
                    'placeholder' => 'Ми робимо тільки те, що реально працює...',
                    'rows' => 3,
                    'required' => 1,
                ),
                array(
                    'key' => 'field_whyus_item_bg_image',
                    'label' => 'Фоновое изображение',
                    'name' => 'bg_image',
                    'type' => 'image',
                    'instructions' => 'Фоновое изображение для элемента (опционально, для элементов с эффектами)',
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_whyus_item_css_classes',
                    'label' => 'CSS классы',
                    'name' => 'css_classes',
                    'type' => 'text',
                    'instructions' => 'CSS классы для элемента (например: "colorist item-3 i1" для элементов с эффектами)',
                    'default_value' => '',
                    'placeholder' => 'colorist item-3 i1',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_whyus_item_has_light',
                    'label' => 'Эффекты света',
                    'name' => 'has_light',
                    'type' => 'true_false',
                    'instructions' => 'Включить эффекты света для элемента',
                    'default_value' => 0,
                    'ui' => 1,
                    'required' => 0,
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options',
            ),
        ),
    ),
    'menu_order' => 2,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Настройки для секции "Почему мы" на главной странице',
));

// Группа полей для Push Start секции
acf_add_local_field_group(array(
    'key' => 'group_pushstart_section',
    'title' => 'Push Start Section - Секция формы',
    'fields' => array(
        // Изображение курсора
        array(
            'key' => 'field_pushstart_cursor_image',
            'label' => 'Изображение курсора',
            'name' => 'pushstart_cursor_image',
            'type' => 'image',
            'instructions' => 'Изображение курсора (если не указано, будет использовано изображение по умолчанию)',
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'required' => 0,
        ),
        // Заголовок
        array(
            'key' => 'field_pushstart_title_group',
            'label' => 'Заголовок',
            'name' => 'pushstart_title_group',
            'type' => 'group',
            'instructions' => 'Настройки заголовка секции',
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_pushstart_title_line1',
                    'label' => 'Первая строка',
                    'name' => 'line1',
                    'type' => 'text',
                    'instructions' => 'Первая строка заголовка (например: "PUSH-СТАРТ")',
                    'default_value' => 'PUSH-СТАРТ',
                    'placeholder' => 'PUSH-СТАРТ',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_pushstart_title_line2',
                    'label' => 'Вторая строка',
                    'name' => 'line2',
                    'type' => 'text',
                    'instructions' => 'Вторая строка заголовка (например: "ДЛЯ ТВОГО БРЕНДУ")',
                    'default_value' => 'ДЛЯ ТВОГО БРЕНДУ',
                    'placeholder' => 'ДЛЯ ТВОГО БРЕНДУ',
                    'required' => 1,
                ),
            ),
        ),
        // Описание
        array(
            'key' => 'field_pushstart_description',
            'label' => 'Описание',
            'name' => 'pushstart_description',
            'type' => 'textarea',
            'instructions' => 'Текст описания в секции',
            'default_value' => 'Залиш свій телефон і ім\'я, і ми швидко зв\'яжемося з тобою, щоб зрозуміти твої цілі, підібрати найефективнішу стратегію, показати, як твої соцмережі можуть реально продавати.',
            'rows' => 4,
            'required' => 1,
        ),
        // Группа: Форма
        array(
            'key' => 'field_pushstart_form_group',
            'label' => 'Настройки формы',
            'name' => 'pushstart_form_group',
            'type' => 'group',
            'instructions' => 'Настройки формы обратной связи',
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_pushstart_form_name_placeholder',
                    'label' => 'Плейсхолдер для имени',
                    'name' => 'name_placeholder',
                    'type' => 'text',
                    'instructions' => 'Текст плейсхолдера для поля имени',
                    'default_value' => 'Ваше Ім\'я',
                    'placeholder' => 'Ваше Ім\'я',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_pushstart_form_phone_placeholder',
                    'label' => 'Плейсхолдер для телефона',
                    'name' => 'phone_placeholder',
                    'type' => 'text',
                    'instructions' => 'Текст плейсхолдера для поля телефона',
                    'default_value' => 'Номер телефону',
                    'placeholder' => 'Номер телефону',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_pushstart_form_button_text',
                    'label' => 'Текст кнопки',
                    'name' => 'button_text',
                    'type' => 'text',
                    'instructions' => 'Текст на кнопке отправки',
                    'default_value' => 'Зв\'язатись з нами',
                    'placeholder' => 'Зв\'язатись з нами',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_pushstart_form_action',
                    'label' => 'Action формы',
                    'name' => 'form_action',
                    'type' => 'url',
                    'instructions' => 'URL для отправки формы (оставьте пустым для текущей страницы)',
                    'default_value' => '',
                    'placeholder' => '',
                    'required' => 0,
                ),
            ),
        ),
        // Социальная ссылка
        array(
            'key' => 'field_pushstart_social_link',
            'label' => 'Социальная ссылка',
            'name' => 'pushstart_social_link',
            'type' => 'url',
            'instructions' => 'Ссылка на социальную сеть (Telegram, WhatsApp и т.д.)',
            'default_value' => '#',
            'placeholder' => '#',
            'required' => 0,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options',
            ),
        ),
    ),
    'menu_order' => 3,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Настройки для секции формы "Push Start" на главной странице',
));

// Группа полей для Cases секции
acf_add_local_field_group(array(
    'key' => 'group_cases_section',
    'title' => 'Cases Section - Секция кейсов',
    'fields' => array(
        // Заголовок
        array(
            'key' => 'field_cases_title_group',
            'label' => 'Заголовок',
            'name' => 'cases_title_group',
            'type' => 'group',
            'instructions' => 'Настройки заголовка секции',
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_cases_title_part1',
                    'label' => 'Первая часть',
                    'name' => 'part1',
                    'type' => 'text',
                    'instructions' => 'Первая часть заголовка (например: "Наші")',
                    'default_value' => 'Наші',
                    'placeholder' => 'Наші',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_cases_title_part2',
                    'label' => 'Вторая часть',
                    'name' => 'part2',
                    'type' => 'text',
                    'instructions' => 'Вторая часть заголовка (например: "Кейси")',
                    'default_value' => 'Кейси',
                    'placeholder' => 'Кейси',
                    'required' => 1,
                ),
            ),
        ),
        // Описание
        array(
            'key' => 'field_cases_description',
            'label' => 'Описание',
            'name' => 'cases_description',
            'type' => 'textarea',
            'instructions' => 'Текст описания в секции кейсов',
            'default_value' => 'Ми створюємо стратегії, які приносять реальні результати. Подивись, як ми допомагаємо брендам розвиватися в соціальних мережах, формувати впізнаваність і збільшувати продажі.',
            'rows' => 4,
            'required' => 1,
        ),
        // Кнопки фильтров
        array(
            'key' => 'field_cases_filter_buttons',
            'label' => 'Кнопки фильтров',
            'name' => 'cases_filter_buttons',
            'type' => 'repeater',
            'instructions' => 'Добавьте кнопки фильтров для категорий кейсов',
            'layout' => 'table',
            'button_label' => 'Добавить кнопку',
            'sub_fields' => array(
                array(
                    'key' => 'field_cases_filter_button_text',
                    'label' => 'Текст кнопки',
                    'name' => 'text',
                    'type' => 'text',
                    'instructions' => 'Текст на кнопке фильтра',
                    'default_value' => '',
                    'placeholder' => 'SMM-консалтинг',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_cases_filter_button_index',
                    'label' => 'Индекс слайда',
                    'name' => 'slide_index',
                    'type' => 'number',
                    'instructions' => 'Индекс слайда для фильтрации (data-slide-index)',
                    'default_value' => 0,
                    'min' => 0,
                    'required' => 1,
                ),
            ),
        ),
        // Карточки кейсов
        array(
            'key' => 'field_cases_cards',
            'label' => 'Карточки кейсов',
            'name' => 'cases_cards',
            'type' => 'repeater',
            'instructions' => 'Добавьте карточки кейсов. Если не заполнено, будут использованы карточки по умолчанию.',
            'layout' => 'block',
            'button_label' => 'Добавить кейс',
            'collapsed' => 'field_cases_card_title',
            'sub_fields' => array(
                array(
                    'key' => 'field_cases_card_title',
                    'label' => 'Заголовок',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => 'Заголовок кейса',
                    'default_value' => '',
                    'placeholder' => 'СТРАТЕГІЯ РОСТУ ДЛЯ GLOWUP STUDIO',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_cases_card_description',
                    'label' => 'Описание',
                    'name' => 'description',
                    'type' => 'textarea',
                    'instructions' => 'Описание кейса',
                    'default_value' => '',
                    'placeholder' => 'Ми допомогли сформувати сильний бренд...',
                    'rows' => 4,
                    'required' => 1,
                ),
                array(
                    'key' => 'field_cases_card_button_text',
                    'label' => 'Текст кнопки',
                    'name' => 'button_text',
                    'type' => 'text',
                    'instructions' => 'Текст на кнопке "Детальніше"',
                    'default_value' => 'Детальніше',
                    'placeholder' => 'Детальніше',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_cases_card_kpi',
                    'label' => 'KPI метрики',
                    'name' => 'kpi',
                    'type' => 'repeater',
                    'instructions' => 'Добавьте KPI метрики для кейса',
                    'layout' => 'table',
                    'button_label' => 'Добавить метрику',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_cases_card_kpi_value',
                            'label' => 'Значение',
                            'name' => 'value',
                            'type' => 'text',
                            'instructions' => 'Значение метрики (например: "+450", "320%")',
                            'default_value' => '',
                            'placeholder' => '+450',
                            'required' => 1,
                        ),
                        array(
                            'key' => 'field_cases_card_kpi_label',
                            'label' => 'Подпись',
                            'name' => 'label',
                            'type' => 'text',
                            'instructions' => 'Подпись метрики (например: "продажів за місяць")',
                            'default_value' => '',
                            'placeholder' => 'продажів за місяць',
                            'required' => 1,
                        ),
                    ),
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options',
            ),
        ),
    ),
    'menu_order' => 4,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Настройки для секции кейсов на главной странице',
));

// Группа полей для Actors секции
acf_add_local_field_group(array(
    'key' => 'group_actors_section',
    'title' => 'Actors Section - Секция актеров',
    'fields' => array(
        // Эмодзи изображение
        array(
            'key' => 'field_actors_emoji',
            'label' => 'Эмодзи изображение',
            'name' => 'actors_emoji',
            'type' => 'image',
            'instructions' => 'Изображение эмодзи для секции (если не указано, будет использовано изображение по умолчанию)',
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'required' => 0,
        ),
        // Заголовок
        array(
            'key' => 'field_actors_title_group',
            'label' => 'Заголовок',
            'name' => 'actors_title_group',
            'type' => 'group',
            'instructions' => 'Настройки заголовка секции',
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_actors_title_part1',
                    'label' => 'Первая часть',
                    'name' => 'part1',
                    'type' => 'text',
                    'instructions' => 'Первая часть заголовка (например: "наші")',
                    'default_value' => 'наші',
                    'placeholder' => 'наші',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_actors_title_part2',
                    'label' => 'Вторая часть (в span)',
                    'name' => 'part2',
                    'type' => 'text',
                    'instructions' => 'Вторая часть заголовка, которая будет в span (например: "актори")',
                    'default_value' => 'актори',
                    'placeholder' => 'актори',
                    'required' => 1,
                ),
            ),
        ),
        // Подзаголовок
        array(
            'key' => 'field_actors_subtitle',
            'label' => 'Подзаголовок',
            'name' => 'actors_subtitle',
            'type' => 'text',
            'instructions' => 'Подзаголовок секции',
            'default_value' => 'Команда, яка вміє працювати на камеру.',
            'placeholder' => 'Команда, яка вміє працювати на камеру.',
            'required' => 1,
        ),
        // Repeater для актеров
        array(
            'key' => 'field_actors_items',
            'label' => 'Актеры',
            'name' => 'actors_items',
            'type' => 'repeater',
            'instructions' => 'Добавьте актеров для слайдера. Если не заполнено, будут использованы актеры по умолчанию.',
            'layout' => 'block',
            'button_label' => 'Добавить актера',
            'collapsed' => 'field_actors_item_title',
            'sub_fields' => array(
                array(
                    'key' => 'field_actors_item_image',
                    'label' => 'Фото актера',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => 'Фотография актера',
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_actors_item_title',
                    'label' => 'Заголовок',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => 'Заголовок актера (например: "#Актор 1")',
                    'default_value' => '',
                    'placeholder' => '#Актор 1',
                    'required' => 1,
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options',
            ),
        ),
    ),
    'menu_order' => 5,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Настройки для секции актеров на главной странице',
));

// Группа полей для Collab секции
acf_add_local_field_group(array(
    'key' => 'group_collab_section',
    'title' => 'Collab Section - Секция этапов сотрудничества',
    'fields' => array(
        // Заголовок
        array(
            'key' => 'field_collab_title_group',
            'label' => 'Заголовок',
            'name' => 'collab_title_group',
            'type' => 'group',
            'instructions' => 'Настройки заголовка секции',
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_collab_title_part1',
                    'label' => 'Первая часть',
                    'name' => 'part1',
                    'type' => 'text',
                    'instructions' => 'Первая часть заголовка (например: "етапи")',
                    'default_value' => 'етапи',
                    'placeholder' => 'етапи',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_collab_title_part2',
                    'label' => 'Вторая часть (в span)',
                    'name' => 'part2',
                    'type' => 'text',
                    'instructions' => 'Вторая часть заголовка, которая будет в span (например: "співпраці")',
                    'default_value' => 'співпраці',
                    'placeholder' => 'співпраці',
                    'required' => 1,
                ),
            ),
        ),
        // Подзаголовок
        array(
            'key' => 'field_collab_subtitle',
            'label' => 'Подзаголовок',
            'name' => 'collab_subtitle',
            'type' => 'text',
            'instructions' => 'Подзаголовок секции',
            'default_value' => 'Ми розробляємо кожен крок співпраці з тобою, щоб створити найкращий результат.',
            'placeholder' => 'Ми розробляємо кожен крок співпраці з тобою, щоб створити найкращий результат.',
            'required' => 1,
        ),
        // Кнопки
        array(
            'key' => 'field_collab_buttons',
            'label' => 'Кнопки',
            'name' => 'collab_buttons',
            'type' => 'repeater',
            'instructions' => 'Добавьте кнопки (обычно 3: Push, your, business)',
            'layout' => 'table',
            'button_label' => 'Добавить кнопку',
            'sub_fields' => array(
                array(
                    'key' => 'field_collab_button_text',
                    'label' => 'Текст',
                    'name' => 'text',
                    'type' => 'text',
                    'instructions' => 'Текст на кнопке',
                    'default_value' => '',
                    'placeholder' => 'Push',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_collab_button_class',
                    'label' => 'CSS класс',
                    'name' => 'css_class',
                    'type' => 'text',
                    'instructions' => 'CSS класс для кнопки (например: button-1, button-2, button-3)',
                    'default_value' => '',
                    'placeholder' => 'button-1',
                    'required' => 1,
                ),
            ),
        ),
        // Этапы сотрудничества
        array(
            'key' => 'field_collab_steps',
            'label' => 'Этапы сотрудничества',
            'name' => 'collab_steps',
            'type' => 'repeater',
            'instructions' => 'Добавьте этапы сотрудничества. Если не заполнено, будут использованы этапы по умолчанию.',
            'layout' => 'block',
            'button_label' => 'Добавить этап',
            'collapsed' => 'field_collab_step_title',
            'sub_fields' => array(
                array(
                    'key' => 'field_collab_step_number',
                    'label' => 'Номер',
                    'name' => 'number',
                    'type' => 'text',
                    'instructions' => 'Номер этапа (например: "01", "02")',
                    'default_value' => '',
                    'placeholder' => '01',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_collab_step_title',
                    'label' => 'Заголовок',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => 'Заголовок этапа',
                    'default_value' => '',
                    'placeholder' => 'Бриф',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_collab_step_description',
                    'label' => 'Описание',
                    'name' => 'description',
                    'type' => 'textarea',
                    'instructions' => 'Описание этапа',
                    'default_value' => '',
                    'placeholder' => 'Заповнюєш форму, де розповідаєш про бізнес...',
                    'rows' => 3,
                    'required' => 1,
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options',
            ),
        ),
    ),
    'menu_order' => 6,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Настройки для секции этапов сотрудничества на главной странице',
));

// Группа полей для FAQ секции
acf_add_local_field_group(array(
    'key' => 'group_faq_section',
    'title' => 'FAQ Section - Секция FAQ',
    'fields' => array(
        // Заголовок
        array(
            'key' => 'field_faq_title',
            'label' => 'Заголовок',
            'name' => 'faq_title',
            'type' => 'text',
            'instructions' => 'Заголовок секции FAQ',
            'default_value' => 'FAQ',
            'placeholder' => 'FAQ',
            'required' => 1,
        ),
        // Папки (folders)
        array(
            'key' => 'field_faq_folders',
            'label' => 'Папки FAQ',
            'name' => 'faq_folders',
            'type' => 'repeater',
            'instructions' => 'Добавьте папки с вопросами. Если не заполнено, будут использованы папки по умолчанию.',
            'layout' => 'block',
            'button_label' => 'Добавить папку',
            'collapsed' => 'field_faq_folder_tab_title',
            'sub_fields' => array(
                array(
                    'key' => 'field_faq_folder_type',
                    'label' => 'Тип папки',
                    'name' => 'folder_type',
                    'type' => 'select',
                    'instructions' => 'Выберите тип папки: обычная с вопросами или контакты',
                    'choices' => array(
                        'questions' => 'Обычная (с вопросами)',
                        'contacts' => 'Контакты',
                    ),
                    'default_value' => 'questions',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_faq_folder_tab_title',
                    'label' => 'Заголовок вкладки',
                    'name' => 'tab_title',
                    'type' => 'text',
                    'instructions' => 'Заголовок вкладки папки (оставьте пустым для папки контактов)',
                    'default_value' => '',
                    'placeholder' => 'SMM-консалтинг',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_faq_folder_type',
                                'operator' => '==',
                                'value' => 'questions',
                            ),
                        ),
                    ),
                ),
                array(
                    'key' => 'field_faq_folder_color',
                    'label' => 'Цвет папки',
                    'name' => 'color',
                    'type' => 'select',
                    'instructions' => 'Выберите цвет папки',
                    'choices' => array(
                        'black' => 'Черный',
                        'orange' => 'Оранжевый',
                    ),
                    'default_value' => 'black',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_faq_folder_number',
                    'label' => 'Номер папки',
                    'name' => 'number',
                    'type' => 'number',
                    'instructions' => 'Номер папки для CSS класса (folder--1, folder--2 и т.д.)',
                    'default_value' => 1,
                    'min' => 1,
                    'required' => 1,
                ),
                array(
                    'key' => 'field_faq_folder_image_type',
                    'label' => 'Тип изображения',
                    'name' => 'image_type',
                    'type' => 'select',
                    'instructions' => 'Выберите тип изображения: одно изображение или несколько (socials)',
                    'choices' => array(
                        'single' => 'Одно изображение',
                        'multiple' => 'Несколько изображений (socials)',
                    ),
                    'default_value' => 'single',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_faq_folder_image',
                    'label' => 'Изображение',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => 'Изображение для папки (используется если выбран тип "Одно изображение")',
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_faq_folder_image_type',
                                'operator' => '==',
                                'value' => 'single',
                            ),
                        ),
                    ),
                ),
                array(
                    'key' => 'field_faq_folder_socials',
                    'label' => 'Изображения соцсетей',
                    'name' => 'socials',
                    'type' => 'repeater',
                    'instructions' => 'Добавьте изображения соцсетей (используется если выбран тип "Несколько изображений")',
                    'layout' => 'table',
                    'button_label' => 'Добавить изображение',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_faq_folder_social_image',
                            'label' => 'Изображение',
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => 'Изображение соцсети',
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'required' => 1,
                        ),
                    ),
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_faq_folder_image_type',
                                'operator' => '==',
                                'value' => 'multiple',
                            ),
                        ),
                    ),
                ),
                array(
                    'key' => 'field_faq_folder_items',
                    'label' => 'Вопросы',
                    'name' => 'items',
                    'type' => 'repeater',
                    'instructions' => 'Добавьте вопросы для этой папки',
                    'layout' => 'table',
                    'button_label' => 'Добавить вопрос',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_faq_folder_item_text',
                            'label' => 'Текст вопроса',
                            'name' => 'text',
                            'type' => 'text',
                            'instructions' => 'Текст вопроса',
                            'default_value' => '',
                            'placeholder' => '01/Що входить у послугу SMM-консалтингу?',
                            'required' => 1,
                        ),
                        array(
                            'key' => 'field_faq_folder_item_link',
                            'label' => 'Ссылка',
                            'name' => 'link',
                            'type' => 'url',
                            'instructions' => 'Ссылка на вопрос',
                            'default_value' => '#',
                            'placeholder' => '#',
                            'required' => 0,
                        ),
                    ),
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_faq_folder_type',
                                'operator' => '==',
                                'value' => 'questions',
                            ),
                        ),
                    ),
                ),
                // Поля для папки контактов
                array(
                    'key' => 'field_faq_folder_contacts_group',
                    'label' => 'Контакты',
                    'name' => 'contacts_group',
                    'type' => 'group',
                    'instructions' => 'Настройки контактов для папки',
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_faq_folder_contacts_title',
                            'label' => 'Заголовок',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => 'Заголовок блока контактов',
                            'default_value' => 'контакти',
                            'placeholder' => 'контакти',
                            'required' => 1,
                        ),
                        array(
                            'key' => 'field_faq_folder_contacts_description',
                            'label' => 'Описание',
                            'name' => 'description',
                            'type' => 'textarea',
                            'instructions' => 'Описание блока контактов',
                            'default_value' => 'Хочеш обговорити проект або просто дізнатися, як ми можемо допомогти твоєму бізнесу рости? Зв\'яжись з нами будь-яким зручним способом — ми швидко відповімо!',
                            'rows' => 3,
                            'required' => 1,
                        ),
                        array(
                            'key' => 'field_faq_folder_contacts_buttons',
                            'label' => 'Кнопки действий',
                            'name' => 'action_buttons',
                            'type' => 'repeater',
                            'instructions' => 'Добавьте кнопки действий (например: "Заповнити бриф", "Зв\'язатись з нами")',
                            'layout' => 'table',
                            'button_label' => 'Добавить кнопку',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_faq_folder_contacts_button_text',
                                    'label' => 'Текст кнопки',
                                    'name' => 'text',
                                    'type' => 'text',
                                    'instructions' => 'Текст на кнопке',
                                    'default_value' => '',
                                    'placeholder' => 'Заповнити бриф',
                                    'required' => 1,
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_faq_folder_contacts_list',
                            'label' => 'Список контактов',
                            'name' => 'contacts_list',
                            'type' => 'repeater',
                            'instructions' => 'Добавьте контакты (telegram, email, телефон и т.д.)',
                            'layout' => 'table',
                            'button_label' => 'Добавить контакт',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_faq_folder_contacts_list_name',
                                    'label' => 'Название',
                                    'name' => 'name',
                                    'type' => 'text',
                                    'instructions' => 'Название контакта (например: "telegram", "email")',
                                    'default_value' => '',
                                    'placeholder' => 'telegram',
                                    'required' => 1,
                                ),
                                array(
                                    'key' => 'field_faq_folder_contacts_list_value',
                                    'label' => 'Значение',
                                    'name' => 'value',
                                    'type' => 'text',
                                    'instructions' => 'Значение контакта (например: "@pushsmmagency", "pushsmmagency@gmail.com")',
                                    'default_value' => '',
                                    'placeholder' => '@pushsmmagency',
                                    'required' => 1,
                                ),
                            ),
                        ),
                    ),
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_faq_folder_type',
                                'operator' => '==',
                                'value' => 'contacts',
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options',
            ),
        ),
    ),
    'menu_order' => 7,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Настройки для секции FAQ на главной странице',
));

// Группа полей для Bonus секции
acf_add_local_field_group(array(
    'key' => 'group_bonus_section',
    'title' => 'Bonus Section - Секция бонуса',
    'fields' => array(
        // Заголовок
        array(
            'key' => 'field_bonus_title_group',
            'label' => 'Заголовок',
            'name' => 'bonus_title_group',
            'type' => 'group',
            'instructions' => 'Настройки заголовка секции',
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_bonus_title_first',
                    'label' => 'Первая строка',
                    'name' => 'first',
                    'type' => 'text',
                    'instructions' => 'Первая строка заголовка',
                    'default_value' => 'Натисни на подарунок, щоб',
                    'placeholder' => 'Натисни на подарунок, щоб',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_bonus_title_second',
                    'label' => 'Вторая строка',
                    'name' => 'second',
                    'type' => 'text',
                    'instructions' => 'Вторая строка заголовка',
                    'default_value' => 'отримати бонус',
                    'placeholder' => 'отримати бонус',
                    'required' => 1,
                ),
            ),
        ),
        // Изображения
        array(
            'key' => 'field_bonus_image_close',
            'label' => 'Изображение закрытого подарка',
            'name' => 'bonus_image_close',
            'type' => 'image',
            'instructions' => 'Изображение закрытого подарка (если не указано, будет использовано изображение по умолчанию)',
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'required' => 0,
        ),
        array(
            'key' => 'field_bonus_image_open',
            'label' => 'Изображение открытого подарка',
            'name' => 'bonus_image_open',
            'type' => 'image',
            'instructions' => 'Изображение открытого подарка (если не указано, будет использовано изображение по умолчанию)',
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'required' => 0,
        ),
        // Заголовок контента
        array(
            'key' => 'field_bonus_content_title',
            'label' => 'Заголовок контента',
            'name' => 'bonus_content_title',
            'type' => 'text',
            'instructions' => 'Заголовок, который отображается внутри открытого подарка',
            'default_value' => 'Бонус',
            'placeholder' => 'Бонус',
            'required' => 1,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options',
            ),
        ),
    ),
    'menu_order' => 8,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Настройки для секции бонуса на главной странице',
));

// Создаем страницу опций, если её нет
if( function_exists('acf_add_options_page') ) {
    acf_add_options_page(array(
        'page_title'    => 'Настройки темы',
        'menu_title'    => 'Настройки темы',
        'menu_slug'     => 'acf-options',
        'capability'    => 'edit_posts',
        'redirect'      => false
    ));
}

endif;

